config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'homepage#index'

  get 'categories' => 'category#index'
  get 'category/:category' => 'category#show', as: 'category'
  patch 'borrow/:id' => 'transactions#borrow', as: 'borrow'

  devise_for :users

  resources :feedbacks
  resources :transactions
  resources :users, only: %i[index show]
end

app/models/feedback.rb
class Feedback < ApplicationRecord
    belongs_to :user
    belongs_to :listing, class_name: :Transaction, foreign_key: "transaction_id"
    # belongs_to :thing

    validates :rating, numericality: {greater_than: 0, less_than_or_equal_to: 5,  only_integer: true }

    validates :comment, length: {in: 0..280}

    # def feedback_user_id
    #   set_transaction
    #   if current_user.id == @lender.id
    #     @feedback_id = @borrower.id
    #   elsif current_user.id == @borrower.id
    #     @feedback_id = @lender.id
    #   end
    # end
end

app/controllers/feedbacks_controller.rb
# frozen_string_literal: true

# :nodoc:
class FeedbacksController < ApplicationController
  before_action :set_feedback, only: %i[show edit update destroy]

  # GET /feedbacks
  # GET /feedbacks.json
  def index
    @feedbacks = Feedback.all
  end

  # GET /feedbacks/1
  # GET /feedbacks/1.json
  def show; end

  # GET /feedbacks/new
  def new
    @feedback = Feedback.new
  end

  # GET /feedbacks/1/edit
  def edit; end

  # POST /feedbacks
  # POST /feedbacks.json
  def create
    @feedback = Feedback.new(feedback_params)
    respond_to do |format|
      if @feedback.save
        Transaction.update(@feedback.transaction_id, :has_lender_feedback => "True")
        format.html { redirect_to transaction_path(@feedback.transaction_id), notice: 'Feedback was successfully created.' }
        format.json { render :show, status: :created, location: @feedback }
      else
        format.html { redirect_to transaction_path(@feedback.transaction_id) }
        flash[:message] = @feedback.errors.full_messages
      end
    end
  end

  # PATCH/PUT /feedbacks/1
  # PATCH/PUT /feedbacks/1.json
  def update
    respond_to do |format|
      if @feedback.update(feedback_params)
        format.html { redirect_to transaction_path(@feedback.transaction_id), notice: 'Feedback was successfully updated.' }
        format.json { render :show, status: :ok, location: @feedback }
      else
        format.html { render :edit }
        format.json { render json: @feedback.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /feedbacks/1
  # DELETE /feedbacks/1.json
  def destroy
    @feedback.destroy
    respond_to do |format|
      format.html { redirect_to feedbacks_url, notice: 'Feedback was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_feedback
    @feedback = Feedback.find(params[:id])
  end

  # Never trust parameters from the scary internet, only allow the white list through.
  def feedback_params
    params.require(:feedback).permit(:user_id, :rating, :transaction_id, :comment)
  end
end

app/helpers/feedbacks_helper.rb
module FeedbacksHelper
end

app/views/feedbacks/_form.html.erb
<%= form_with(model: feedback, local: true) do |form| %>
  <% if feedback.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(feedback.errors.count, "error") %> prohibited this feedback from being saved:</h2>

      <ul>
      <% feedback.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.number_field :user_id %>
  </div>

  <div class="field">
    <%= form.label :rating %>
    <%= form.number_field :rating %>
  </div>

  <div class="field">
    <%= form.label :transaction_id %>
    <%= form.number_field :transaction_id %>
  </div>

  <div class="field">
    <%= form.label :comment %>
    <%= form.text_field :comment %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/feedbacks/_form.html.haml
.card
  .card-content
    =flash[:message]
    = form_with(model: feedback, local: true) do |f|
      - if feedback.errors.any?
        
        #error_explanation
          %h2= "#{pluralize(feedback.errors.count, "error")} prohibited this feedback from being saved:"
          %ul
          - feedback.errors.full_messages.each do |message|
            %li= message
      .input-field
        = f.label "Rating(Out of 5)"
        = f.number_field :rating
      .input-field
        = f.label :comment
        = f.text_field :comment
      - if feedback.user_id.nil?
        = f.hidden_field :user_id, value: current_user.id
        = f.hidden_field :transaction_id, value: params[:id]
      - else
        = f.hidden_field :user_id
        = f.hidden_field :transaction_id, value: params[:id]
      .card-action
        = f.submit "Submit", class: "btn waves-effect waves-light green white-text"

app/views/feedbacks/_list.html.haml
-@feedback.each do |f|
    =image_tag(f.user.avatar.url)
    =f.user.fname
    =f.user.lname 
    =f.user.email
    =f.comment

app/views/feedbacks/_single.html.haml
%li.collection-item.avatar
  = image_tag feedback.user.avatar.url, class: 'circle'
  %span.title
    = link_to "#{feedback.user.fname} #{feedback.user.lname}", feedback.user
  %p= "Rating: #{feedback.rating} out of 5"
  %p= feedback.comment

app/views/feedbacks/edit.html.erb
<h1>Editing Feedback</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Show', @feedback %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/edit.html.haml
.section
  .container
    %h1 Editing Feedback
    = render 'form', feedback: @feedback, transaction: @transaction
    = link_to 'Show', @feedback, transaction: @transaction

app/views/feedbacks/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Feedbacks</h1>

<table>
  <thead>
    <tr>
      <th>User</th>
      <th>Rating</th>
      <th>Transaction</th>
      <th>Comment</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @feedbacks.each do |feedback| %>
      <tr>
        <td><%= feedback.user_id %></td>
        <td><%= feedback.rating %></td>
        <td><%= feedback.transaction_id %></td>
        <td><%= feedback.comment %></td>
        <td><%= link_to 'Show', feedback %></td>
        <td><%= link_to 'Edit', edit_feedback_path(feedback) %></td>
        <td><%= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Feedback', new_feedback_path %>

app/views/feedbacks/index.html.haml
.section
  .container
    %p#notice= notice
    %h1 Feedbacks

.section
  .container
    %table
      %thead
        %tr
          %th User
          %th Rating
          %th Transaction
          %th Comment
          %th{colspan: 3}
      %tbody
        - @feedbacks.each do |feedback|
          %tr
            %td= feedback.user_id
            %td= feedback.rating
            %td= feedback.transaction_id
            %td= feedback.comment
            %td= link_to 'Show', feedback
            %td= link_to 'Edit', edit_feedback_path(feedback)
            %td= link_to 'Destroy', feedback, method: :delete, data: { confirm: 'Are you sure?' }

.section
  .container
    = link_to 'New Feedback', new_feedback_path

app/views/feedbacks/new.html.erb
<h1>New Feedback</h1>

<%= render 'form', feedback: @feedback %>

<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/new.html.haml
.section
  .container
    %h1 New Feedback
    = render 'form', feedback: Feedback.new

app/views/feedbacks/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @feedback.user_id %>
</p>

<p>
  <strong>Rating:</strong>
  <%= @feedback.rating %>
</p>

<p>
  <strong>Transaction:</strong>
  <%= @feedback.transaction_id %>
</p>

<p>
  <strong>Comment:</strong>
  <%= @feedback.comment %>
</p>

<%= link_to 'Edit', edit_feedback_path(@feedback) %> |
<%= link_to 'Back', feedbacks_path %>

app/views/feedbacks/show.html.haml
.section
  .container
    %p#notice= notice
    %ul.collection
      = render 'single', feedback: @feedback