config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'homepage#index'

  get 'categories' => 'category#index'
  get 'category/:category' => 'category#show', as: 'category'
  patch 'borrow/:id' => 'transactions#borrow', as: 'borrow'

  devise_for :users

  resources :feedbacks
  resources :transactions
  resources :users, only: %i[index show]
end

app/controllers/transactions_controller.rb
# frozen_string_literal: true

# :nodoc:
class TransactionsController < ApplicationController
  before_action :set_transaction, only: %i[show edit update destroy]

  # GET /transactions
  # GET /transactions.json
  def index
    @transactions = Transaction.all
  end

  # GET /transactions/1
  # GET /transactions/1.json
  def show
    set_transaction
    @lender = @transaction.lender
    @borrower = @transaction.borrower
    @feedback = @transaction.feedbacks
  end

  # GET /transactions/new
  def new
    @transaction = Transaction.new
  end

  # GET /transactions/1/edit
  def edit; end

  def borrow
    Transaction.update(params[:id], borrower_id: current_user.id, status: 'Closed')
    redirect_to transaction_path(params[:id])
  end

  # POST /transactions
  # POST /transactions.json
  def create
    @transaction = Transaction.new(transaction_params)
    @transaction.lender_id = current_user.id
    @transaction.action = 'Lend'
    @transaction.status = 'Open'
    # t.datetime "expires_at"
    # t.datetime "starts_at"
    if @transaction.expires_at <= @transaction.starts_at 
      flash[:notice] = "Expires at needs to be greater than starts at. Start date also can't be before today."
      redirect_to new_transaction_path
    else
        respond_to do |format|
          if @transaction.save
            format.html { redirect_to @transaction, notice: 'Transaction was successfully created.' }
            format.json { render :show, status: :created, location: @transaction }
          else
            flash[:notice] = @transaction.errors.full_messages
            format.html { render :new }
            format.json { render json: @transaction.errors, status: :unprocessable_entity }
          end
        end
      end
  end

  # PATCH/PUT /transactions/1
  # PATCH/PUT /transactions/1.json
  def update
    respond_to do |format|
      if @transaction.update(transaction_params)
        format.html { redirect_to @transaction, notice: 'Transaction was successfully updated.' }
        format.json { render :show, status: :ok, location: @transaction }
      else
        format.html { render :edit }
        format.json { render json: @transaction.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /transactions/1
  # DELETE /transactions/1.json
  def destroy
    @transaction.destroy
    respond_to do |format|
      format.html { redirect_to transactions_url, notice: 'Transaction was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  # Use callbacks to share common setup or constraints between actions.
  def set_transaction
    @transaction = Transaction.find(params[:id])
  end

  # def set_user
    # set_transaction
    # if current_user == @lender.id
    #   user_id == @borrower.id
    # elsif current_user == @borrower.id
    #   user_id == @lender.id
    # end
  # end

  # Never trust parameters from the scary internet, only allow the white list through.
  def transaction_params
    params.require(:transaction).permit(:borrower_id, :lender_id, :status, :expires_at, :starts_at, :action, :has_borrower_feedback, :has_lender_feedback, :category, :title, :body, :item_location, :loan_duration, :day_rate, :avatar)
  end
end

app/helpers/transactions_helper.rb
module TransactionsHelper
end

app/views/transactions/_debuglist.html.haml
%table
  %thead
    %tr
      %th Borrower
      %th Lender
      %th Status
      %th Expires at
      %th Starts at
      %th Type
      %th Has borrower feedback
      %th Has lender feedback
      %th Category
      %th Title
      %th Body
      %th Item location
      %th Loan duration
      %th Day rate
      %th{colspan:  3}
  %tbody
    - @transactions.each do |t|
      %tr
        %td= t.borrower_id
        %td= t.lender_id
        %td= t.status
        %td= t.expires_at
        %td= t.starts_at
        %td= t.action
        %td= t.has_borrower_feedback
        %td= t.has_lender_feedback
        %td= t.category
        %td= t.title
        %td= t.body
        %td= t.item_location
        %td= t.loan_duration
        %td= t.day_rate
        %td= link_to 'Show', t
        %td= link_to 'Edit', edit_transaction_path(t)
        %td= link_to 'Destroy', t, method: :delete, data: { confirm: 'Are you sure?' }

app/views/transactions/_debugsingle.haml
.section
  .container
    %p#notice= notice
    %ul.collection.with-header
      %li.collection-header
        %h4
          = link_to transaction.title, transaction_path(transaction.id)
      %li.collection-item
        %strong Borrower:
        = transaction.borrower_id
      %li.collection-item
        %strong Lender:
        = transaction.lender_id
      %li.collection-item
        %strong Status:
        = transaction.status
      %li.collection-item
        %strong Expires at:
        = transaction.expires_at
      %li.collection-item
        %strong Starts at:
        = transaction.starts_at
      %li.collection-item
        %strong Action:
        = transaction.action
      %li.collection-item
        %strong Has borrower feedback:
        = transaction.has_borrower_feedback
      %li.collection-item
        %strong Has lender feedback:
        = transaction.has_lender_feedback
      %li.collection-item
        %strong Category:
        = transaction.category
      %li.collection-item
        %strong Body:
        = transaction.body
      %li.collection-item
        %strong Item location:
        = transaction.item_location
      %li.collection-item
        %strong Loan duration:
        = transaction.loan_duration
      %li.collection-item
        %strong Day rate:
        = transaction.day_rate
      %li.collection-item
        = image_tag (transaction.avatar.url)

app/views/transactions/_feedback.html.haml
.card
  .card-content
    = form_with(model: feedback, local: true) do |f|
      - if feedback.errors.any?
        #error_explanation
          %h2= "#{pluralize(feedback.errors.count, "error")} prohibited this feedback from being saved:"
          %ul
          - feedback.errors.full_messages.each do |message|
            %li= message
      - if current_user.id == @lender.id
        .input-field
          -# = f.label :user_id
          = f.hidden_field :user_id, :value => @borrower.id
      - elsif current_user.id == @borrower.id
        .input-field
          -# = f.label :user_id
          = f.hidden_field :user_id, :value => @lender.id
      .input-field
        = f.label :rating
        = f.number_field :rating
      .input-field
        -# = f.label :transaction_id
        = f.hidden_field :transaction_id, :value => @transaction.id
      - if @transaction.has_borrower_feedback == false && current_user.id == @lender.id
        .input-field
          -# = f.label :transaction_id
          = f.hidden_field :has_borrower_feedback, :value => true
      - elsif @transaction.has_lender_feedback == false && current_user.id == @borrower.id
        .input-field
          -# = f.label :transaction_id
          = f.hidden_field :has_borrower_feedback, :value => true
      .input-field
        = f.label :comment
        = f.text_field :comment
      .card-action
        = f.submit "Submit", class: "btn waves-effect waves-light green white-text"

app/views/transactions/_form.html.haml
.card
  .card-content
    = flash[:notice]
    = form_with(model: transaction, local: true) do |f|
      - if transaction.errors.any?
        #error_explanation
          %h2= "#{pluralize(transaction.errors.count, "error")} prohibited this transaction from being saved:"
          %ul
            = transaction.errors.full_messages.each do |message|
              %li= message
      .row
        .col.s12.l6
          .input-field.datepicker.active
            = f.label :starts_at
            = f.text_field :starts_at
        .col.s12.l6
          .input-field.datepicker.active
            = f.label :expires_at
            = f.text_field :expires_at
      .input-field
        = select("transaction", "category", options_for_select(CATEGORY))
        = f.label :category
      .input-field
        = f.label :title
        = f.text_field :title
      .input-field
        = f.text_area :body, class: 'materialize-textarea'
        = f.label :body
      .input-field#gmap-form
        = f.hidden_field :item_location
        %input#pac-input{class: 'controls browser-default', type: 'text', placeholder: 'Enter a location'}
        #map
        #infowindow-content
          %span#place-name.title
          %br
          %span#place-address
      .input-field
        = f.label :loan_duration
        = f.number_field :loan_duration
      .input-field
        = f.label :day_rate
        = f.text_field :day_rate
      .input-field.file-field
        .btn
          %span Upload an Image
          = f.file_field :avatar
        .file-path-wrapper
          %input{type: "text", class: "file-path"}
          = f.hidden_field :status
      = f.hidden_field :action
      = f.hidden_field :lender_id
      = f.hidden_field :borrower_id
      = f.hidden_field :has_lender_feedback
      = f.hidden_field :has_borrower_feedback
      .card-action
        = f.submit "Submit", class: "btn waves-effect waves-light green white-text"
-# Call GMaps Code.
%script initMap()

app/views/transactions/_list.html.haml
-if @transactions.count > 1
  - left,right = @transactions.in_groups_of( (@transactions.count/2.0).ceil, false )
  .row
    .col.s6
      - left.each do |t|
        = render 'transactions/single', transaction: t
    .col.s6
      - right.each do |t|
        = render 'transactions/single', transaction: t
-elsif @transactions.count == 1
  .row
    .col.s12
      = render 'transactions/single', transaction: @transactions[0]
-else
  -# No transactions

-# Call GMaps Code.
%script initMap()

app/views/transactions/_new.html.haml
.card
  .card-content
    = form_with(model: transaction, url: new_transaction_path, local: true) do |f|
      - if transaction.errors.any?
        #error_explanation
          %h2= "#{pluralize(transaction.errors.count, "error")} prohibited this transaction from being saved:"
          %ul
            = transaction.errors.full_messages.each do |message|
              %li= message
      -# .input-field
      -#   = f.label :borrower_id
      -#   = f.number_field :borrower_id
      -# .input-field
      -#   = f.label :lender_id
      -#   = f.number_field :lender_id
      -# .input-field
      -#   = f.label :status
      -#   = f.text_field :status
      .input-field
        = f.label :starts_at
        = f.datetime_select :starts_at
      .input-field
        = f.label :expires_at
        = f.datetime_select :expires_at
      .input-field
        = f.label :action
        = select("transaction", "action", options_for_select(ACTION))
      .input-field
        = f.label :category
        = select("transaction", "category", options_for_select(CATEGORY))
      .input-field
        = f.label :title
        = f.text_field :title
      .input-field
        = f.label :body
        = f.text_area :body
      .input-field
        = f.label :item_location
        = f.text_field :item_location
      .input-field
        = f.label :loan_duration
        = f.number_field :loan_duration
      .input-field
        = f.label :day_rate
        = f.text_field :day_rate
      .input-field
        = f.label :avatar
        = f.file_field :avatar
      -# .input-field.checkbox
      -#   = f.label :has_borrower_feedback
      -#   = f.check_box :has_borrower_feedback
      -# .input-field.checkbox
      -#   = f.label :has_lender_feedback
      -#   = f.check_box :has_lender_feedback
      .card-action
        = f.submit "Submit", class: "btn waves-effect waves-light green white-text"

app/views/transactions/_show_feedback.html.haml
.section
  .container
    %p#notice= notice
    %ul.collection
      %li.collection-item
        %strong User:
        = @feedback.user_id
      %li.collection-item
        %strong Rating:
        = @feedback.rating
      %li.collection-item
        %strong Transaction:
        = @feedback.transaction_id
      %li.collection-item
        %strong Comment:
        = @feedback.comment
      %li.collection-item
        = link_to 'Edit', edit_feedback_path(@feedback)
        = link_to 'Back', feedbacks_path

app/views/transactions/_single.haml
.card
  .card-image
    = image_tag (transaction.avatar.url)
  .card-content
    .row
      .col.s12.l6
        %span.card-title= link_to transaction.title, transaction_path(transaction.id)
        %p
          %strong Category:
          = link_to transaction.category, '/category/' + transaction.category
        %p= transaction.body
        %p
          Lended by
          = link_to "#{transaction.lender.fname} #{transaction.lender.lname}", user_path(transaction.lender)
        %p
        -if transaction.borrower != nil
          %p
            Borrowed by
            = link_to "#{transaction.borrower.fname} #{transaction.borrower.lname}", user_path(transaction.borrower)
        -else
          %p Not Borrowed Yet
        %p
          %strong Due Date:
          = "#{transaction.loan_duration} days after loan begins."
      .col.s12.l6.gmap-show
        .gmap{data: {placeid: transaction.item_location} }
  -# Let the owner of this transaction edit it.
  - if transaction.lender_id == current_user.id
    .card-action
      = link_to 'Edit', edit_transaction_path(transaction)
  -# If the transaction is open, let anyone but the lender borrow it.
  - if transaction.status == "Open" && transaction.lender_id != current_user.id
    .card-action
      = button_to 'Borrow this!', borrow_path(transaction), method: :patch, class: "btn waves-effect waves-light green white-text"

app/views/transactions/edit.html.haml
- if user_signed_in? && current_user.id == @transaction.lender_id
  -# If the current user is the lender for this transaction, let them edit:
  .section
    .container
      %h1 Editing Transaction
      = render 'form', transaction: @transaction
- else
  -# Otherwise, let them know we're onto them:
  .section
    .container.center-align
      %h1 Whoops!
      %p It looks like you tried to edit a transaction you don't own.
      %a{href: new_transaction_path} Perhaps you'd like to create a new transaction instead?

app/views/transactions/index.html.haml
.section
  .container
    %p#notice= notice
    %h1 All Transactions
    = render 'list', locals: {transactions: @transactions}

app/views/transactions/new.html.haml
.section
  .container
    %h1 New Transaction
    = render 'form', transaction: Transaction.new
    = link_to 'Back', transactions_path

app/views/transactions/show.html.haml
.section
  .container
    %p#notice= notice
    %h1= @transaction.title
.section
  .container
    .row
      .col.s12.l10.offset-l1
        = render 'single', transaction: @transaction
        - if @transaction.has_borrower_feedback || @transaction.has_lender_feedback
          %ul.collection.z-depth-1
            - @transaction.feedbacks.each do |fb|
              = render 'feedbacks/single', feedback: fb
      -if @borrower != nil && @transaction.has_lender_feedback == nil
        .col.s12.l10.offset-l1
          - if current_user.id == @lender.id
            %h2= "Leave Feedback for #{@borrower.fname}"
            = render 'feedbacks/form', feedback: Feedback.new, transaction: @transaction
          -if current_user.id == @borrower.id
            %h2= "Leave Feedback for #{@lender.fname}"
            = render 'feedbacks/form', feedback: Feedback.new, transaction: @transaction
-# Call GMaps Code.
%script initMap()