config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root 'homepage#index'

  get 'categories' => 'category#index'
  get 'category/:category' => 'category#show', as: 'category'
  patch 'borrow/:id' => 'transactions#borrow', as: 'borrow'

  devise_for :users

  resources :feedbacks
  resources :transactions
  resources :users, only: %i[index show]
end

app/views/layouts/_footer.html.haml
- if user_signed_in?
  .fixed-action-btn
    %a.btn-floating.btn-large
      %i.large.material-icons menu
    %ul
      %li
        = link_to new_transaction_path, data:{position: 'top', tooltip: 'New Transaction'}, class: 'btn-floating green tooltipped' do
          %i.material-icons mode_edit
      %li
        = link_to user_path(current_user), data:{position: 'top', tooltip: 'Your Profile'}, class: 'btn-floating yellow darken-2 tooltipped' do
          %i.material-icons account_circle
      %li
        = link_to categories_path, data: {position: 'top', tooltip: 'Browse Categories'}, class: 'btn-floating blue tooltipped' do
          %i.material-icons list
      %li
        = link_to destroy_user_session_path, data:{position: 'top', tooltip: 'Logout'}, method: :delete, class: 'btn-floating red tooltipped' do
          %i.material-icons exit_to_app
%footer#main-footer
  .container
    .row
      #footer-credits
        %p.center-align
          Created by:
          %a{href: 'https://github.com/josephcardillo'} Joe Cardillo
          |
          %a{href: 'https://github.com/noah-callahan'} Noah Callahan
          |
          %a{href: 'https://github.com/delster'} David Elster

app/views/layouts/_header.html.haml
%header#main-header
  %nav
    .nav-wrapper
      %form
        .input-field
          = search_field 'search', nil
          %label.label-icon
            %i.material-icons search
          %i.material-icons close

-# Include the GMaps JavaScript (poorly, refactor this 🤮)
%script{src: 'https://maps.googleapis.com/maps/api/js?key=AIzaSyAF88J2F_1qnz8gSc1Jyt8ECVtcx2q4Jv0&libraries=places'}
= javascript_include_tag 'gmaps'

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en" }
  %head
    %title Neighborli
    = csrf_meta_tags
    = csp_meta_tag
    %meta{ :charset => "utf-8" }
    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }
    = stylesheet_link_tag "application", media: 'all', 'data-turbolinks-track' => 'reload'
    = javascript_include_tag "application", media: 'all', 'data-turbolinks-track' => 'reload'
  %body
    = render 'layouts/header'
    %main= yield
    = render 'layouts/footer'